name: 'Cached composer install'
description: 'Install composer dependencies, cached by the lockfile hash'
inputs:
  no_dev:
    default: 'false'
    description: Skip installing dev dependencies?

runs:
  using: 'composite'
  steps:
    - name: Get composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Fetch composer cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-default-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-default

    - name: Install composer dependencies
      shell: bash
      env:
        DEV_OPTION: ${{ inputs.no_dev == 'true' && '--no-dev' || '' }}
      run: |
        composer install $DEV_OPTION --no-interaction --no-progress
