name: 'Cached composer install'
description: 'Install composer dependencies, cached by the lockfile hash'
runs:
  using: 'composite'
  steps:
    - name: Get composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Fetch composer cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-default-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-default

    - name: Install composer dependencies
      shell: bash
      run: composer install --no-interaction --no-progress
