name: Release

on:
  push:

jobs:

  tag-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Re-tag v1
        # Note, the current `v1` tag won't have been pulled by "checkout" above, so we can just create a new one
        run: git tag v1 && git show --no-patch v1

      - name: Publish v1
        run: git push -f origin v1
